/* src/StoreCount/index.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	append,
	component_subscribe,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	safe_not_equal,
	set_data,
	space,
	text,
	transition_in,
	transition_out
} from "../../web_modules/svelte/internal.js";

import store from "./store.js";
import Incrementer from "./Incrementer.js";
import Decrementer from "./Decrementer.js";
import PageTitle from "../components/PageTitle.js";

function create_fragment(ctx) {
	let pagetitle;
	let t0;
	let decrementer;
	let t1;
	let span;
	let t2;
	let t3;
	let t4;
	let incrementer;
	let current;
	pagetitle = new PageTitle({ props: { title: "Counter Using Store" } });
	decrementer = new Decrementer({});
	incrementer = new Incrementer({});

	return {
		c() {
			create_component(pagetitle.$$.fragment);
			t0 = space();
			create_component(decrementer.$$.fragment);
			t1 = space();
			span = element("span");
			t2 = text("StoreCount: ");
			t3 = text(/*$store*/ ctx[0]);
			t4 = space();
			create_component(incrementer.$$.fragment);
		},
		m(target, anchor) {
			mount_component(pagetitle, target, anchor);
			insert(target, t0, anchor);
			mount_component(decrementer, target, anchor);
			insert(target, t1, anchor);
			insert(target, span, anchor);
			append(span, t2);
			append(span, t3);
			insert(target, t4, anchor);
			mount_component(incrementer, target, anchor);
			current = true;
		},
		p(ctx, [dirty]) {
			if (!current || dirty & /*$store*/ 1) set_data(t3, /*$store*/ ctx[0]);
		},
		i(local) {
			if (current) return;
			transition_in(pagetitle.$$.fragment, local);
			transition_in(decrementer.$$.fragment, local);
			transition_in(incrementer.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(pagetitle.$$.fragment, local);
			transition_out(decrementer.$$.fragment, local);
			transition_out(incrementer.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(pagetitle, detaching);
			if (detaching) detach(t0);
			destroy_component(decrementer, detaching);
			if (detaching) detach(t1);
			if (detaching) detach(span);
			if (detaching) detach(t4);
			destroy_component(incrementer, detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let $store;
	component_subscribe($$self, store, $$value => $$invalidate(0, $store = $$value));
	return [$store];
}

class StoreCount extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default StoreCount;