import './App.css.proxy.js';
/* src/App.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	noop,
	safe_not_equal,
	space,
	transition_in,
	transition_out
} from "../web_modules/svelte/internal.js";

import Routes from "./Routes.js";
import SiteNav from "./SiteNav.js";
import "../web_modules/minireset.css.js";

function create_fragment(ctx) {
	let header;
	let sitenav;
	let t0;
	let main;
	let routes;
	let t1;
	let footer;
	let current;
	sitenav = new SiteNav({});
	routes = new Routes({});

	return {
		c() {
			header = element("header");
			create_component(sitenav.$$.fragment);
			t0 = space();
			main = element("main");
			create_component(routes.$$.fragment);
			t1 = space();
			footer = element("footer");
			footer.innerHTML = `<p>I am the footer</p>`;
		},
		m(target, anchor) {
			insert(target, header, anchor);
			mount_component(sitenav, header, null);
			insert(target, t0, anchor);
			insert(target, main, anchor);
			mount_component(routes, main, null);
			insert(target, t1, anchor);
			insert(target, footer, anchor);
			current = true;
		},
		p: noop,
		i(local) {
			if (current) return;
			transition_in(sitenav.$$.fragment, local);
			transition_in(routes.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(sitenav.$$.fragment, local);
			transition_out(routes.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(header);
			destroy_component(sitenav);
			if (detaching) detach(t0);
			if (detaching) detach(main);
			destroy_component(routes);
			if (detaching) detach(t1);
			if (detaching) detach(footer);
		}
	};
}

class App extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default App;