/* src/Counter.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	append,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	listen,
	mount_component,
	safe_not_equal,
	set_data,
	space,
	text,
	transition_in,
	transition_out
} from "../web_modules/svelte/internal.js";

import PageTitle from "./components/PageTitle.js";

function create_fragment(ctx) {
	let pagetitle;
	let t0;
	let button;
	let t1;
	let t2;
	let t3;
	let p;
	let em;
	let t4;
	let t5;
	let current;
	let mounted;
	let dispose;
	pagetitle = new PageTitle({ props: { title: "Simple Counter" } });

	return {
		c() {
			create_component(pagetitle.$$.fragment);
			t0 = space();
			button = element("button");
			t1 = text("Counter: ");
			t2 = text(/*count*/ ctx[0]);
			t3 = space();
			p = element("p");
			em = element("em");
			t4 = text("Squared: ");
			t5 = text(/*squared*/ ctx[1]);
		},
		m(target, anchor) {
			mount_component(pagetitle, target, anchor);
			insert(target, t0, anchor);
			insert(target, button, anchor);
			append(button, t1);
			append(button, t2);
			insert(target, t3, anchor);
			insert(target, p, anchor);
			append(p, em);
			append(em, t4);
			append(em, t5);
			current = true;

			if (!mounted) {
				dispose = listen(button, "click", /*handleClick*/ ctx[2]);
				mounted = true;
			}
		},
		p(ctx, [dirty]) {
			if (!current || dirty & /*count*/ 1) set_data(t2, /*count*/ ctx[0]);
			if (!current || dirty & /*squared*/ 2) set_data(t5, /*squared*/ ctx[1]);
		},
		i(local) {
			if (current) return;
			transition_in(pagetitle.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(pagetitle.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(pagetitle, detaching);
			if (detaching) detach(t0);
			if (detaching) detach(button);
			if (detaching) detach(t3);
			if (detaching) detach(p);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let count = 0;
	const handleClick = () => $$invalidate(0, count++, count);
	let squared;

	$$self.$$.update = () => {
		if ($$self.$$.dirty & /*count*/ 1) {
			$: $$invalidate(1, squared = count ** 2);
		}
	};

	return [count, squared, handleClick];
}

class Counter extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Counter;