/* src/Form.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	add_flush_callback,
	append,
	bind,
	binding_callbacks,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	safe_not_equal,
	set_data,
	space,
	text,
	transition_in,
	transition_out
} from "../web_modules/svelte/internal.js";

import Form from "./components/Form.js";
import Question from "./components/Question.js";

function create_default_slot(ctx) {
	let fieldset;
	let legend;
	let t1;
	let question0;
	let updating_value;
	let t2;
	let question1;
	let updating_value_1;
	let t3;
	let question2;
	let updating_value_2;
	let t4;
	let question3;
	let updating_value_3;
	let t5;
	let question4;
	let updating_value_4;
	let t6;
	let question5;
	let updating_value_5;
	let t7;
	let question6;
	let updating_value_6;
	let t8;
	let question7;
	let updating_value_7;
	let t9;
	let question8;
	let updating_value_8;
	let t10;
	let question9;
	let updating_value_9;
	let t11;
	let question10;
	let updating_checked;
	let t12;
	let question11;
	let updating_value_10;
	let current;

	function question0_value_binding(value) {
		/*question0_value_binding*/ ctx[8].call(null, value);
	}

	let question0_props = {
		label: "First Name",
		max: "30",
		type: "text"
	};

	if (/*values*/ ctx[0].firstname !== void 0) {
		question0_props.value = /*values*/ ctx[0].firstname;
	}

	question0 = new Question({ props: question0_props });
	binding_callbacks.push(() => bind(question0, "value", question0_value_binding));

	function question1_value_binding(value) {
		/*question1_value_binding*/ ctx[9].call(null, value);
	}

	let question1_props = {
		label: "Last Name With Long Label",
		min: "2"
	};

	if (/*values*/ ctx[0].lastname !== void 0) {
		question1_props.value = /*values*/ ctx[0].lastname;
	}

	question1 = new Question({ props: question1_props });
	binding_callbacks.push(() => bind(question1, "value", question1_value_binding));

	function question2_value_binding(value) {
		/*question2_value_binding*/ ctx[10].call(null, value);
	}

	let question2_props = {
		label: "Email",
		placeholder: "foo@bar.com",
		type: "email"
	};

	if (/*values*/ ctx[0].email !== void 0) {
		question2_props.value = /*values*/ ctx[0].email;
	}

	question2 = new Question({ props: question2_props });
	binding_callbacks.push(() => bind(question2, "value", question2_value_binding));

	function question3_value_binding(value) {
		/*question3_value_binding*/ ctx[11].call(null, value);
	}

	let question3_props = {
		label: "What say you?",
		type: "select",
		options: ["yes", "no", "maybe"]
	};

	if (/*values*/ ctx[0].kinda !== void 0) {
		question3_props.value = /*values*/ ctx[0].kinda;
	}

	question3 = new Question({ props: question3_props });
	binding_callbacks.push(() => bind(question3, "value", question3_value_binding));

	function question4_value_binding(value) {
		/*question4_value_binding*/ ctx[12].call(null, value);
	}

	let question4_props = {
		label: "Beatles",
		placeholder: "Pick a few",
		multi: true,
		type: "select",
		options: ["John", "Paul", "George", "Ringo"]
	};

	if (/*values*/ ctx[0].beatles !== void 0) {
		question4_props.value = /*values*/ ctx[0].beatles;
	}

	question4 = new Question({ props: question4_props });
	binding_callbacks.push(() => bind(question4, "value", question4_value_binding));

	function question5_value_binding(value) {
		/*question5_value_binding*/ ctx[13].call(null, value);
	}

	let question5_props = {
		label: "Color",
		placeholder: "Choose a favorite",
		type: "select",
		options: ["red", "blue", "green", "yellow", "orange", "purple"]
	};

	if (/*values*/ ctx[0].color !== void 0) {
		question5_props.value = /*values*/ ctx[0].color;
	}

	question5 = new Question({ props: question5_props });
	binding_callbacks.push(() => bind(question5, "value", question5_value_binding));

	function question6_value_binding(value) {
		/*question6_value_binding*/ ctx[14].call(null, value);
	}

	let question6_props = {
		label: "Start Date",
		type: "date",
		min: /*today*/ ctx[3]
	};

	if (/*values*/ ctx[0].startdate !== void 0) {
		question6_props.value = /*values*/ ctx[0].startdate;
	}

	question6 = new Question({ props: question6_props });
	binding_callbacks.push(() => bind(question6, "value", question6_value_binding));

	function question7_value_binding(value) {
		/*question7_value_binding*/ ctx[15].call(null, value);
	}

	let question7_props = {
		label: "End Date",
		type: "date",
		min: /*values*/ ctx[0].startdate
	};

	if (/*values*/ ctx[0].enddate !== void 0) {
		question7_props.value = /*values*/ ctx[0].enddate;
	}

	question7 = new Question({ props: question7_props });
	binding_callbacks.push(() => bind(question7, "value", question7_value_binding));

	function question8_value_binding(value) {
		/*question8_value_binding*/ ctx[16].call(null, value);
	}

	let question8_props = {
		label: "Number One",
		type: "number",
		min: "5",
		step: "0.1"
	};

	if (/*values*/ ctx[0].number1 !== void 0) {
		question8_props.value = /*values*/ ctx[0].number1;
	}

	question8 = new Question({ props: question8_props });
	binding_callbacks.push(() => bind(question8, "value", question8_value_binding));

	function question9_value_binding(value) {
		/*question9_value_binding*/ ctx[17].call(null, value);
	}

	let question9_props = {
		label: "Number Two",
		type: "number",
		min: /*values*/ ctx[0].number1,
		max: 100 - /*values*/ ctx[0].number1,
		required: false
	};

	if (/*values*/ ctx[0].number2 !== void 0) {
		question9_props.value = /*values*/ ctx[0].number2;
	}

	question9 = new Question({ props: question9_props });
	binding_callbacks.push(() => bind(question9, "value", question9_value_binding));

	function question10_checked_binding(value) {
		/*question10_checked_binding*/ ctx[18].call(null, value);
	}

	let question10_props = {
		label: "I agree to this very long hard-to-read and repetative condition. I\n    agree to this very long hard-to-read and repetative condition. I agree\n    to this very long hard-to-read and repetative condition. I agree to this\n    very long hard-to-read and repetative condition. I agree to this very\n    long hard-to-read and repetative condition.",
		type: "checkbox",
		required: false
	};

	if (/*values*/ ctx[0].agree !== void 0) {
		question10_props.checked = /*values*/ ctx[0].agree;
	}

	question10 = new Question({ props: question10_props });
	binding_callbacks.push(() => bind(question10, "checked", question10_checked_binding));
	question10.$on("change", /*handleAgreeChange*/ ctx[4]);

	function question11_value_binding(value) {
		/*question11_value_binding*/ ctx[19].call(null, value);
	}

	let question11_props = {
		show: !/*values*/ ctx[0].agree,
		label: "Explain",
		type: "textarea"
	};

	if (/*values*/ ctx[0].whynot !== void 0) {
		question11_props.value = /*values*/ ctx[0].whynot;
	}

	question11 = new Question({ props: question11_props });
	binding_callbacks.push(() => bind(question11, "value", question11_value_binding));

	return {
		c() {
			fieldset = element("fieldset");
			legend = element("legend");
			legend.textContent = "Your Info";
			t1 = space();
			create_component(question0.$$.fragment);
			t2 = space();
			create_component(question1.$$.fragment);
			t3 = space();
			create_component(question2.$$.fragment);
			t4 = space();
			create_component(question3.$$.fragment);
			t5 = space();
			create_component(question4.$$.fragment);
			t6 = space();
			create_component(question5.$$.fragment);
			t7 = space();
			create_component(question6.$$.fragment);
			t8 = space();
			create_component(question7.$$.fragment);
			t9 = space();
			create_component(question8.$$.fragment);
			t10 = space();
			create_component(question9.$$.fragment);
			t11 = space();
			create_component(question10.$$.fragment);
			t12 = space();
			create_component(question11.$$.fragment);
		},
		m(target, anchor) {
			insert(target, fieldset, anchor);
			append(fieldset, legend);
			append(fieldset, t1);
			mount_component(question0, fieldset, null);
			append(fieldset, t2);
			mount_component(question1, fieldset, null);
			append(fieldset, t3);
			mount_component(question2, fieldset, null);
			append(fieldset, t4);
			mount_component(question3, fieldset, null);
			append(fieldset, t5);
			mount_component(question4, fieldset, null);
			append(fieldset, t6);
			mount_component(question5, fieldset, null);
			append(fieldset, t7);
			mount_component(question6, fieldset, null);
			append(fieldset, t8);
			mount_component(question7, fieldset, null);
			append(fieldset, t9);
			mount_component(question8, fieldset, null);
			append(fieldset, t10);
			mount_component(question9, fieldset, null);
			append(fieldset, t11);
			mount_component(question10, fieldset, null);
			append(fieldset, t12);
			mount_component(question11, fieldset, null);
			current = true;
		},
		p(ctx, dirty) {
			const question0_changes = {};

			if (!updating_value && dirty & /*values*/ 1) {
				updating_value = true;
				question0_changes.value = /*values*/ ctx[0].firstname;
				add_flush_callback(() => updating_value = false);
			}

			question0.$set(question0_changes);
			const question1_changes = {};

			if (!updating_value_1 && dirty & /*values*/ 1) {
				updating_value_1 = true;
				question1_changes.value = /*values*/ ctx[0].lastname;
				add_flush_callback(() => updating_value_1 = false);
			}

			question1.$set(question1_changes);
			const question2_changes = {};

			if (!updating_value_2 && dirty & /*values*/ 1) {
				updating_value_2 = true;
				question2_changes.value = /*values*/ ctx[0].email;
				add_flush_callback(() => updating_value_2 = false);
			}

			question2.$set(question2_changes);
			const question3_changes = {};

			if (!updating_value_3 && dirty & /*values*/ 1) {
				updating_value_3 = true;
				question3_changes.value = /*values*/ ctx[0].kinda;
				add_flush_callback(() => updating_value_3 = false);
			}

			question3.$set(question3_changes);
			const question4_changes = {};

			if (!updating_value_4 && dirty & /*values*/ 1) {
				updating_value_4 = true;
				question4_changes.value = /*values*/ ctx[0].beatles;
				add_flush_callback(() => updating_value_4 = false);
			}

			question4.$set(question4_changes);
			const question5_changes = {};

			if (!updating_value_5 && dirty & /*values*/ 1) {
				updating_value_5 = true;
				question5_changes.value = /*values*/ ctx[0].color;
				add_flush_callback(() => updating_value_5 = false);
			}

			question5.$set(question5_changes);
			const question6_changes = {};

			if (!updating_value_6 && dirty & /*values*/ 1) {
				updating_value_6 = true;
				question6_changes.value = /*values*/ ctx[0].startdate;
				add_flush_callback(() => updating_value_6 = false);
			}

			question6.$set(question6_changes);
			const question7_changes = {};
			if (dirty & /*values*/ 1) question7_changes.min = /*values*/ ctx[0].startdate;

			if (!updating_value_7 && dirty & /*values*/ 1) {
				updating_value_7 = true;
				question7_changes.value = /*values*/ ctx[0].enddate;
				add_flush_callback(() => updating_value_7 = false);
			}

			question7.$set(question7_changes);
			const question8_changes = {};

			if (!updating_value_8 && dirty & /*values*/ 1) {
				updating_value_8 = true;
				question8_changes.value = /*values*/ ctx[0].number1;
				add_flush_callback(() => updating_value_8 = false);
			}

			question8.$set(question8_changes);
			const question9_changes = {};
			if (dirty & /*values*/ 1) question9_changes.min = /*values*/ ctx[0].number1;
			if (dirty & /*values*/ 1) question9_changes.max = 100 - /*values*/ ctx[0].number1;

			if (!updating_value_9 && dirty & /*values*/ 1) {
				updating_value_9 = true;
				question9_changes.value = /*values*/ ctx[0].number2;
				add_flush_callback(() => updating_value_9 = false);
			}

			question9.$set(question9_changes);
			const question10_changes = {};

			if (!updating_checked && dirty & /*values*/ 1) {
				updating_checked = true;
				question10_changes.checked = /*values*/ ctx[0].agree;
				add_flush_callback(() => updating_checked = false);
			}

			question10.$set(question10_changes);
			const question11_changes = {};
			if (dirty & /*values*/ 1) question11_changes.show = !/*values*/ ctx[0].agree;

			if (!updating_value_10 && dirty & /*values*/ 1) {
				updating_value_10 = true;
				question11_changes.value = /*values*/ ctx[0].whynot;
				add_flush_callback(() => updating_value_10 = false);
			}

			question11.$set(question11_changes);
		},
		i(local) {
			if (current) return;
			transition_in(question0.$$.fragment, local);
			transition_in(question1.$$.fragment, local);
			transition_in(question2.$$.fragment, local);
			transition_in(question3.$$.fragment, local);
			transition_in(question4.$$.fragment, local);
			transition_in(question5.$$.fragment, local);
			transition_in(question6.$$.fragment, local);
			transition_in(question7.$$.fragment, local);
			transition_in(question8.$$.fragment, local);
			transition_in(question9.$$.fragment, local);
			transition_in(question10.$$.fragment, local);
			transition_in(question11.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(question0.$$.fragment, local);
			transition_out(question1.$$.fragment, local);
			transition_out(question2.$$.fragment, local);
			transition_out(question3.$$.fragment, local);
			transition_out(question4.$$.fragment, local);
			transition_out(question5.$$.fragment, local);
			transition_out(question6.$$.fragment, local);
			transition_out(question7.$$.fragment, local);
			transition_out(question8.$$.fragment, local);
			transition_out(question9.$$.fragment, local);
			transition_out(question10.$$.fragment, local);
			transition_out(question11.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(fieldset);
			destroy_component(question0);
			destroy_component(question1);
			destroy_component(question2);
			destroy_component(question3);
			destroy_component(question4);
			destroy_component(question5);
			destroy_component(question6);
			destroy_component(question7);
			destroy_component(question8);
			destroy_component(question9);
			destroy_component(question10);
			destroy_component(question11);
		}
	};
}

function create_fragment(ctx) {
	let form;
	let t0;
	let pre;

	let t1_value = JSON.stringify(
		{
			values: /*values*/ ctx[0],
			savedValues: /*savedValues*/ ctx[1],
			submittedValues: /*submittedValues*/ ctx[2]
		},
		null,
		2
	) + "";

	let t1;
	let current;

	form = new Form({
			props: {
				onSubmit: /*onSubmit*/ ctx[7],
				onSave: /*onSave*/ ctx[6],
				onReset: /*onReset*/ ctx[5],
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			}
		});

	return {
		c() {
			create_component(form.$$.fragment);
			t0 = space();
			pre = element("pre");
			t1 = text(t1_value);
		},
		m(target, anchor) {
			mount_component(form, target, anchor);
			insert(target, t0, anchor);
			insert(target, pre, anchor);
			append(pre, t1);
			current = true;
		},
		p(ctx, [dirty]) {
			const form_changes = {};

			if (dirty & /*$$scope, values*/ 2097153) {
				form_changes.$$scope = { dirty, ctx };
			}

			form.$set(form_changes);

			if ((!current || dirty & /*values, savedValues, submittedValues*/ 7) && t1_value !== (t1_value = JSON.stringify(
				{
					values: /*values*/ ctx[0],
					savedValues: /*savedValues*/ ctx[1],
					submittedValues: /*submittedValues*/ ctx[2]
				},
				null,
				2
			) + "")) set_data(t1, t1_value);
		},
		i(local) {
			if (current) return;
			transition_in(form.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(form.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(form, detaching);
			if (detaching) detach(t0);
			if (detaching) detach(pre);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	const today = new Date().toISOString().slice(0, 10);

	const initialValues = {
		firstname: "hello",
		lastname: "world",
		email: "george@beatles.com",
		color: "purple",
		beatles: ["George"],
		startdate: today,
		enddate: today,
		number1: 5,
		number2: null,
		agree: true,
		kinda: "",
		whynot: ""
	};

	let values = { ...initialValues };
	let savedValues = {};
	let submittedValues = {};

	function handleAgreeChange() {
		$$invalidate(0, values.whynot = "", values);
	}

	function onReset() {
		$$invalidate(0, values = { ...initialValues });
	}

	function onSave() {
		$$invalidate(1, savedValues = { ...values });
	}

	function onSubmit() {
		$$invalidate(2, submittedValues = { ...values });
		onReset();
	}

	function question0_value_binding(value) {
		values.firstname = value;
		$$invalidate(0, values);
	}

	function question1_value_binding(value) {
		values.lastname = value;
		$$invalidate(0, values);
	}

	function question2_value_binding(value) {
		values.email = value;
		$$invalidate(0, values);
	}

	function question3_value_binding(value) {
		values.kinda = value;
		$$invalidate(0, values);
	}

	function question4_value_binding(value) {
		values.beatles = value;
		$$invalidate(0, values);
	}

	function question5_value_binding(value) {
		values.color = value;
		$$invalidate(0, values);
	}

	function question6_value_binding(value) {
		values.startdate = value;
		$$invalidate(0, values);
	}

	function question7_value_binding(value) {
		values.enddate = value;
		$$invalidate(0, values);
	}

	function question8_value_binding(value) {
		values.number1 = value;
		$$invalidate(0, values);
	}

	function question9_value_binding(value) {
		values.number2 = value;
		$$invalidate(0, values);
	}

	function question10_checked_binding(value) {
		values.agree = value;
		$$invalidate(0, values);
	}

	function question11_value_binding(value) {
		values.whynot = value;
		$$invalidate(0, values);
	}

	return [
		values,
		savedValues,
		submittedValues,
		today,
		handleAgreeChange,
		onReset,
		onSave,
		onSubmit,
		question0_value_binding,
		question1_value_binding,
		question2_value_binding,
		question3_value_binding,
		question4_value_binding,
		question5_value_binding,
		question6_value_binding,
		question7_value_binding,
		question8_value_binding,
		question9_value_binding,
		question10_checked_binding,
		question11_value_binding
	];
}

class Form_1 extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Form_1;