import './Hello.css.proxy.js';
/* src/Hello.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	attr,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	safe_not_equal,
	space,
	transition_in,
	transition_out
} from "../web_modules/svelte/internal.js";

import PageTitle from "./components/PageTitle.js";

function create_fragment(ctx) {
	let pagetitle;
	let t0;
	let h2;
	let t2;
	let div3;
	let t8;
	let pre;
	let current;

	pagetitle = new PageTitle({
			props: {
				title: `Hello ${/*name*/ ctx[0].toUpperCase()} Page`
			}
		});

	return {
		c() {
			create_component(pagetitle.$$.fragment);
			t0 = space();
			h2 = element("h2");
			h2.textContent = "CSS misc";
			t2 = space();
			div3 = element("div");

			div3.innerHTML = `<div class="svelte-1lyppnd">foo foo foo foo foo foo foo foo</div> 
  <div class="svelte-1lyppnd">barasdfasdfasdf</div> 
  <div class="svelte-1lyppnd">bazasdfasdf</div>`;

			t8 = space();
			pre = element("pre");
			pre.textContent = `${JSON.stringify({ data: /*data*/ ctx[1] }, null, 2)}`;
			attr(h2, "class", "svelte-1lyppnd");
			attr(div3, "class", "wrap svelte-1lyppnd");
		},
		m(target, anchor) {
			mount_component(pagetitle, target, anchor);
			insert(target, t0, anchor);
			insert(target, h2, anchor);
			insert(target, t2, anchor);
			insert(target, div3, anchor);
			insert(target, t8, anchor);
			insert(target, pre, anchor);
			current = true;
		},
		p(ctx, [dirty]) {
			const pagetitle_changes = {};
			if (dirty & /*name*/ 1) pagetitle_changes.title = `Hello ${/*name*/ ctx[0].toUpperCase()} Page`;
			pagetitle.$set(pagetitle_changes);
		},
		i(local) {
			if (current) return;
			transition_in(pagetitle.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(pagetitle.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(pagetitle, detaching);
			if (detaching) detach(t0);
			if (detaching) detach(h2);
			if (detaching) detach(t2);
			if (detaching) detach(div3);
			if (detaching) detach(t8);
			if (detaching) detach(pre);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { name = "World" } = $$props;
	const data = { foo: "foo", bar: "bar", baz: true };

	$$self.$$set = $$props => {
		if ("name" in $$props) $$invalidate(0, name = $$props.name);
	};

	return [name, data];
}

class Hello extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { name: 0 });
	}
}

export default Hello;