/* src/Routes.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	assign,
	check_outros,
	create_component,
	destroy_component,
	detach,
	empty,
	get_spread_object,
	get_spread_update,
	group_outros,
	init,
	insert,
	mount_component,
	safe_not_equal,
	transition_in,
	transition_out
} from "../web_modules/svelte/internal.js";

import navaid from "../web_modules/navaid.js";
import pathname from "./RoutesStore.js";
import Hello from "./Hello.js";
import Counter from "./Counter.js";
import Section from "./Section.js";
import SwapiPerson from "./SwapiPerson.js";
import Things from "./Things.js";
import NotFound from "./NotFound.js";
import StoreCount from "./StoreCount/index.js";
import Form from "./Form.js";

function create_fragment(ctx) {
	let switch_instance;
	let switch_instance_anchor;
	let current;
	const switch_instance_spread_levels = [/*routeArgs*/ ctx[1]];
	var switch_value = /*page*/ ctx[0];

	function switch_props(ctx) {
		let switch_instance_props = {};

		for (let i = 0; i < switch_instance_spread_levels.length; i += 1) {
			switch_instance_props = assign(switch_instance_props, switch_instance_spread_levels[i]);
		}

		return { props: switch_instance_props };
	}

	if (switch_value) {
		switch_instance = new switch_value(switch_props(ctx));
	}

	return {
		c() {
			if (switch_instance) create_component(switch_instance.$$.fragment);
			switch_instance_anchor = empty();
		},
		m(target, anchor) {
			if (switch_instance) {
				mount_component(switch_instance, target, anchor);
			}

			insert(target, switch_instance_anchor, anchor);
			current = true;
		},
		p(ctx, [dirty]) {
			const switch_instance_changes = (dirty & /*routeArgs*/ 2)
			? get_spread_update(switch_instance_spread_levels, [get_spread_object(/*routeArgs*/ ctx[1])])
			: {};

			if (switch_value !== (switch_value = /*page*/ ctx[0])) {
				if (switch_instance) {
					group_outros();
					const old_component = switch_instance;

					transition_out(old_component.$$.fragment, 1, 0, () => {
						destroy_component(old_component, 1);
					});

					check_outros();
				}

				if (switch_value) {
					switch_instance = new switch_value(switch_props(ctx));
					create_component(switch_instance.$$.fragment);
					transition_in(switch_instance.$$.fragment, 1);
					mount_component(switch_instance, switch_instance_anchor.parentNode, switch_instance_anchor);
				} else {
					switch_instance = null;
				}
			} else if (switch_value) {
				switch_instance.$set(switch_instance_changes);
			}
		},
		i(local) {
			if (current) return;
			if (switch_instance) transition_in(switch_instance.$$.fragment, local);
			current = true;
		},
		o(local) {
			if (switch_instance) transition_out(switch_instance.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(switch_instance_anchor);
			if (switch_instance) destroy_component(switch_instance, detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	const router = navaid("/", () => NotFound);
	let page;
	let routeArgs = {};

	const routes = {
		"/": Hello,
		"/counter/simple": Counter,
		"/counter/store": StoreCount,
		"/section": Section,
		"/swapi-person": SwapiPerson,
		"/things/:thing1/:thing2": Things,
		"/form": Form,
		"/*": NotFound
	};

	Object.keys(routes).forEach(path => {
		router.on(path, args => {
			// strip path arguments like /path/:arg1/:arg2
			pathname.set("/" + path.split("/").filter(Boolean).filter(s => !s.startsWith(":")).join("/"));

			$$invalidate(0, page = routes[path]);
			$$invalidate(1, routeArgs = args);
		});
	});

	router.listen();
	return [page, routeArgs];
}

class Routes extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default Routes;