/* src/Section.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	safe_not_equal,
	space,
	transition_in,
	transition_out
} from "../web_modules/svelte/internal.js";

import PageTitle from "./components/PageTitle.js";
import Section from "./components/Section.js";

function create_default_slot(ctx) {
	let p0;
	let t1;
	let p1;

	return {
		c() {
			p0 = element("p");
			p0.textContent = "A slot is sorta like React's \"children\"";
			t1 = space();
			p1 = element("p");
			p1.textContent = "A slot is sorta like React's \"children\"";
		},
		m(target, anchor) {
			insert(target, p0, anchor);
			insert(target, t1, anchor);
			insert(target, p1, anchor);
		},
		d(detaching) {
			if (detaching) detach(p0);
			if (detaching) detach(t1);
			if (detaching) detach(p1);
		}
	};
}

function create_fragment(ctx) {
	let pagetitle;
	let t;
	let section;
	let current;
	pagetitle = new PageTitle({ props: { title: "Section Component" } });

	section = new Section({
			props: {
				title: "Section Title Here",
				$$slots: { default: [create_default_slot] },
				$$scope: { ctx }
			}
		});

	return {
		c() {
			create_component(pagetitle.$$.fragment);
			t = space();
			create_component(section.$$.fragment);
		},
		m(target, anchor) {
			mount_component(pagetitle, target, anchor);
			insert(target, t, anchor);
			mount_component(section, target, anchor);
			current = true;
		},
		p(ctx, [dirty]) {
			const section_changes = {};

			if (dirty & /*$$scope*/ 1) {
				section_changes.$$scope = { dirty, ctx };
			}

			section.$set(section_changes);
		},
		i(local) {
			if (current) return;
			transition_in(pagetitle.$$.fragment, local);
			transition_in(section.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(pagetitle.$$.fragment, local);
			transition_out(section.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(pagetitle, detaching);
			if (detaching) detach(t);
			destroy_component(section, detaching);
		}
	};
}

class Section_1 extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, null, create_fragment, safe_not_equal, {});
	}
}

export default Section_1;