import './SiteNav.css.proxy.js';
/* src/SiteNav.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	append,
	attr,
	bubble,
	component_subscribe,
	destroy_each,
	detach,
	element,
	empty,
	init,
	insert,
	listen,
	noop,
	null_to_empty,
	prevent_default,
	safe_not_equal,
	space,
	text
} from "../web_modules/svelte/internal.js";

import pathname from "./RoutesStore.js";

function get_each_context_1(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[8] = list[i];
	return child_ctx;
}

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[3] = list[i].href;
	child_ctx[4] = list[i].text;
	child_ctx[5] = list[i].children;
	return child_ctx;
}

// (49:6) {:else}
function create_else_block(ctx) {
	let li;
	let a;
	let t0_value = /*text*/ ctx[4] + "";
	let t0;
	let t1;
	let ul;
	let ul_aria_label_value;
	let t2;
	let li_class_value;
	let mounted;
	let dispose;
	let each_value_1 = /*children*/ ctx[5];
	let each_blocks = [];

	for (let i = 0; i < each_value_1.length; i += 1) {
		each_blocks[i] = create_each_block_1(get_each_context_1(ctx, each_value_1, i));
	}

	return {
		c() {
			li = element("li");
			a = element("a");
			t0 = text(t0_value);
			t1 = space();
			ul = element("ul");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			t2 = space();
			attr(a, "aria-haspopup", "true");
			attr(a, "href", "");
			attr(a, "class", "svelte-n30bk");
			attr(ul, "class", "dropdown svelte-n30bk");
			attr(ul, "aria-label", ul_aria_label_value = `${/*text*/ ctx[4]} - submenu`);

			attr(li, "class", li_class_value = "" + (null_to_empty(/*$pathname*/ ctx[0] !== "/" && /*href*/ ctx[3].startsWith(/*$pathname*/ ctx[0])
			? "active"
			: "") + " svelte-n30bk"));
		},
		m(target, anchor) {
			insert(target, li, anchor);
			append(li, a);
			append(a, t0);
			append(li, t1);
			append(li, ul);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}

			append(li, t2);

			if (!mounted) {
				dispose = listen(a, "click", prevent_default(/*click_handler*/ ctx[2]));
				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty & /*nav*/ 2) {
				each_value_1 = /*children*/ ctx[5];
				let i;

				for (i = 0; i < each_value_1.length; i += 1) {
					const child_ctx = get_each_context_1(ctx, each_value_1, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
					} else {
						each_blocks[i] = create_each_block_1(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}

				each_blocks.length = each_value_1.length;
			}

			if (dirty & /*$pathname*/ 1 && li_class_value !== (li_class_value = "" + (null_to_empty(/*$pathname*/ ctx[0] !== "/" && /*href*/ ctx[3].startsWith(/*$pathname*/ ctx[0])
			? "active"
			: "") + " svelte-n30bk"))) {
				attr(li, "class", li_class_value);
			}
		},
		d(detaching) {
			if (detaching) detach(li);
			destroy_each(each_blocks, detaching);
			mounted = false;
			dispose();
		}
	};
}

// (44:6) {#if !children}
function create_if_block(ctx) {
	let li;
	let a;
	let t0_value = /*text*/ ctx[4] + "";
	let t0;
	let a_href_value;
	let t1;
	let li_class_value;

	return {
		c() {
			li = element("li");
			a = element("a");
			t0 = text(t0_value);
			t1 = space();
			attr(a, "href", a_href_value = /*href*/ ctx[3]);
			attr(a, "class", "svelte-n30bk");

			attr(li, "class", li_class_value = "" + (null_to_empty(/*$pathname*/ ctx[0] === "/" && /*href*/ ctx[3] === "/" || /*$pathname*/ ctx[0] !== "/" && /*href*/ ctx[3].startsWith(/*$pathname*/ ctx[0])
			? "active"
			: "") + " svelte-n30bk"));
		},
		m(target, anchor) {
			insert(target, li, anchor);
			append(li, a);
			append(a, t0);
			append(li, t1);
		},
		p(ctx, dirty) {
			if (dirty & /*$pathname*/ 1 && li_class_value !== (li_class_value = "" + (null_to_empty(/*$pathname*/ ctx[0] === "/" && /*href*/ ctx[3] === "/" || /*$pathname*/ ctx[0] !== "/" && /*href*/ ctx[3].startsWith(/*$pathname*/ ctx[0])
			? "active"
			: "") + " svelte-n30bk"))) {
				attr(li, "class", li_class_value);
			}
		},
		d(detaching) {
			if (detaching) detach(li);
		}
	};
}

// (54:12) {#each children as child}
function create_each_block_1(ctx) {
	let li;
	let a;
	let t_value = /*child*/ ctx[8].text + "";
	let t;
	let a_href_value;

	return {
		c() {
			li = element("li");
			a = element("a");
			t = text(t_value);
			attr(a, "href", a_href_value = /*child*/ ctx[8].href);
			attr(a, "class", "svelte-n30bk");
			attr(li, "class", "svelte-n30bk");
		},
		m(target, anchor) {
			insert(target, li, anchor);
			append(li, a);
			append(a, t);
		},
		p: noop,
		d(detaching) {
			if (detaching) detach(li);
		}
	};
}

// (43:4) {#each nav as { href, text, children }}
function create_each_block(ctx) {
	let if_block_anchor;

	function select_block_type(ctx, dirty) {
		if (!/*children*/ ctx[5]) return create_if_block;
		return create_else_block;
	}

	let current_block_type = select_block_type(ctx, -1);
	let if_block = current_block_type(ctx);

	return {
		c() {
			if_block.c();
			if_block_anchor = empty();
		},
		m(target, anchor) {
			if_block.m(target, anchor);
			insert(target, if_block_anchor, anchor);
		},
		p(ctx, dirty) {
			if_block.p(ctx, dirty);
		},
		d(detaching) {
			if_block.d(detaching);
			if (detaching) detach(if_block_anchor);
		}
	};
}

function create_fragment(ctx) {
	let nav_1;
	let ul;
	let each_value = /*nav*/ ctx[1];
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	return {
		c() {
			nav_1 = element("nav");
			ul = element("ul");

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			attr(ul, "class", "svelte-n30bk");
			attr(nav_1, "class", "svelte-n30bk");
		},
		m(target, anchor) {
			insert(target, nav_1, anchor);
			append(nav_1, ul);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(ul, null);
			}
		},
		p(ctx, [dirty]) {
			if (dirty & /*$pathname, nav*/ 3) {
				each_value = /*nav*/ ctx[1];
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(ul, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}

				each_blocks.length = each_value.length;
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(nav_1);
			destroy_each(each_blocks, detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let $pathname;
	component_subscribe($$self, pathname, $$value => $$invalidate(0, $pathname = $$value));

	const nav = [
		{ href: "/", text: "Home" },
		{
			href: "/counter",
			text: "Counters",
			children: [
				{
					href: "/counter/simple",
					text: "Simple Counter"
				},
				{
					href: "/counter/store",
					text: "Store Counter"
				}
			]
		},
		{
			href: "/swapi-person",
			text: "Swapi Person"
		},
		{ href: "/things/foo/bar", text: "Things" },
		{ href: "/section", text: "Section" },
		{ href: "/form", text: "Form" }
	];

	function click_handler(event) {
		bubble($$self, event);
	}

	return [$pathname, nav, click_handler];
}

class SiteNav extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default SiteNav;