import './SwapiPerson.css.proxy.js';
/* src/SwapiPerson.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	append,
	attr,
	create_component,
	destroy_component,
	detach,
	element,
	empty,
	handle_promise,
	init,
	insert,
	listen,
	mount_component,
	noop,
	safe_not_equal,
	set_data,
	space,
	subscribe,
	text,
	transition_in,
	transition_out
} from "../web_modules/svelte/internal.js";

import getData from "./fetcher.js";
import PageTitle from "./components/PageTitle.js";

function create_catch_block(ctx) {
	let p;

	return {
		c() {
			p = element("p");
			p.textContent = "Oops! Error!";
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		p: noop,
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

// (18:0) {:then swapi}
function create_then_block(ctx) {
	let p;
	let t0_value = /*swapi*/ ctx[5].name + "";
	let t0;
	let t1;
	let t2_value = /*swapi*/ ctx[5].birth_year + "";
	let t2;
	let t3;

	return {
		c() {
			p = element("p");
			t0 = text(t0_value);
			t1 = text(" (birth year: ");
			t2 = text(t2_value);
			t3 = text(")");
			attr(p, "class", "character svelte-vt0f7u");
		},
		m(target, anchor) {
			insert(target, p, anchor);
			append(p, t0);
			append(p, t1);
			append(p, t2);
			append(p, t3);
		},
		p(ctx, dirty) {
			if (dirty & /*$data*/ 2 && t0_value !== (t0_value = /*swapi*/ ctx[5].name + "")) set_data(t0, t0_value);
			if (dirty & /*$data*/ 2 && t2_value !== (t2_value = /*swapi*/ ctx[5].birth_year + "")) set_data(t2, t2_value);
		},
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

// (16:14)    <p>Loading...</p> {:then swapi}
function create_pending_block(ctx) {
	let p;

	return {
		c() {
			p = element("p");
			p.textContent = "Loading...";
		},
		m(target, anchor) {
			insert(target, p, anchor);
		},
		p: noop,
		d(detaching) {
			if (detaching) detach(p);
		}
	};
}

function create_fragment(ctx) {
	let pagetitle;
	let t0;
	let button;
	let t1;
	let button_disabled_value;
	let t2;
	let await_block_anchor;
	let promise;
	let current;
	let mounted;
	let dispose;
	pagetitle = new PageTitle({ props: { title: "Random SWAPI Person" } });

	let info = {
		ctx,
		current: null,
		token: null,
		hasCatch: true,
		pending: create_pending_block,
		then: create_then_block,
		catch: create_catch_block,
		value: 5
	};

	handle_promise(promise = /*$data*/ ctx[1], info);

	return {
		c() {
			create_component(pagetitle.$$.fragment);
			t0 = space();
			button = element("button");
			t1 = text("Reload random Star Wars character");
			t2 = space();
			await_block_anchor = empty();
			info.block.c();
			button.disabled = button_disabled_value = !/*$data*/ ctx[1];
		},
		m(target, anchor) {
			mount_component(pagetitle, target, anchor);
			insert(target, t0, anchor);
			insert(target, button, anchor);
			append(button, t1);
			insert(target, t2, anchor);
			insert(target, await_block_anchor, anchor);
			info.block.m(target, info.anchor = anchor);
			info.mount = () => await_block_anchor.parentNode;
			info.anchor = await_block_anchor;
			current = true;

			if (!mounted) {
				dispose = listen(button, "click", /*onClick*/ ctx[2]);
				mounted = true;
			}
		},
		p(new_ctx, [dirty]) {
			ctx = new_ctx;

			if (!current || dirty & /*$data*/ 2 && button_disabled_value !== (button_disabled_value = !/*$data*/ ctx[1])) {
				button.disabled = button_disabled_value;
			}

			info.ctx = ctx;

			if (dirty & /*$data*/ 2 && promise !== (promise = /*$data*/ ctx[1]) && handle_promise(promise, info)) {
				
			} else {
				const child_ctx = ctx.slice();
				child_ctx[5] = info.resolved;
				info.block.p(child_ctx, dirty);
			}
		},
		i(local) {
			if (current) return;
			transition_in(pagetitle.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(pagetitle.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(pagetitle, detaching);
			if (detaching) detach(t0);
			if (detaching) detach(button);
			if (detaching) detach(t2);
			if (detaching) detach(await_block_anchor);
			info.block.d(detaching);
			info.token = null;
			info = null;
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let $data,
		$$unsubscribe_data = noop,
		$$subscribe_data = () => ($$unsubscribe_data(), $$unsubscribe_data = subscribe(data, $$value => $$invalidate(1, $data = $$value)), data);

	$$self.$$.on_destroy.push(() => $$unsubscribe_data());
	const getRandomNumber = () => Math.floor(Math.random() * 10) + 1;
	let randomNumber = getRandomNumber();
	let data = getData(`https://swapi.dev/api/people/${randomNumber}/`);
	$$subscribe_data();

	const onClick = () => {
		randomNumber = getRandomNumber();
		$$subscribe_data($$invalidate(0, data = getData(`https://swapi.dev/api/people/${randomNumber}/`)));
	};

	return [data, $data, onClick];
}

class SwapiPerson extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, {});
	}
}

export default SwapiPerson;