/* src/Things.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	append,
	create_component,
	destroy_component,
	detach,
	element,
	init,
	insert,
	mount_component,
	safe_not_equal,
	set_data,
	space,
	text,
	transition_in,
	transition_out
} from "../web_modules/svelte/internal.js";

import PageTitle from "./components/PageTitle.js";

function create_fragment(ctx) {
	let pagetitle;
	let t0;
	let h20;
	let t1;
	let t2;
	let t3;
	let h21;
	let t4;
	let t5;
	let current;
	pagetitle = new PageTitle({ props: { title: "Things" } });

	return {
		c() {
			create_component(pagetitle.$$.fragment);
			t0 = space();
			h20 = element("h2");
			t1 = text("I am ");
			t2 = text(/*thing1*/ ctx[0]);
			t3 = space();
			h21 = element("h2");
			t4 = text("I am ");
			t5 = text(/*thing2*/ ctx[1]);
		},
		m(target, anchor) {
			mount_component(pagetitle, target, anchor);
			insert(target, t0, anchor);
			insert(target, h20, anchor);
			append(h20, t1);
			append(h20, t2);
			insert(target, t3, anchor);
			insert(target, h21, anchor);
			append(h21, t4);
			append(h21, t5);
			current = true;
		},
		p(ctx, [dirty]) {
			if (!current || dirty & /*thing1*/ 1) set_data(t2, /*thing1*/ ctx[0]);
			if (!current || dirty & /*thing2*/ 2) set_data(t5, /*thing2*/ ctx[1]);
		},
		i(local) {
			if (current) return;
			transition_in(pagetitle.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(pagetitle.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			destroy_component(pagetitle, detaching);
			if (detaching) detach(t0);
			if (detaching) detach(h20);
			if (detaching) detach(t3);
			if (detaching) detach(h21);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { thing1 } = $$props;
	let { thing2 } = $$props;

	$$self.$$set = $$props => {
		if ("thing1" in $$props) $$invalidate(0, thing1 = $$props.thing1);
		if ("thing2" in $$props) $$invalidate(1, thing2 = $$props.thing2);
	};

	return [thing1, thing2];
}

class Things extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { thing1: 0, thing2: 1 });
	}
}

export default Things;