/* src/components/Form.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	append,
	create_component,
	create_slot,
	destroy_component,
	detach,
	element,
	init,
	insert,
	is_function,
	listen,
	mount_component,
	prevent_default,
	run_all,
	safe_not_equal,
	space,
	transition_in,
	transition_out,
	update_slot
} from "../../web_modules/svelte/internal.js";

import FormButtons from "./FormButtons.js";

function create_fragment(ctx) {
	let form;
	let t;
	let formbuttons;
	let current;
	let mounted;
	let dispose;
	const default_slot_template = /*#slots*/ ctx[4].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[3], null);
	formbuttons = new FormButtons({ props: { onSave: /*onSave*/ ctx[1] } });

	return {
		c() {
			form = element("form");
			if (default_slot) default_slot.c();
			t = space();
			create_component(formbuttons.$$.fragment);
		},
		m(target, anchor) {
			insert(target, form, anchor);

			if (default_slot) {
				default_slot.m(form, null);
			}

			append(form, t);
			mount_component(formbuttons, form, null);
			current = true;

			if (!mounted) {
				dispose = [
					listen(form, "submit", prevent_default(function () {
						if (is_function(/*onSubmit*/ ctx[0])) /*onSubmit*/ ctx[0].apply(this, arguments);
					})),
					listen(form, "reset", prevent_default(function () {
						if (is_function(/*onReset*/ ctx[2])) /*onReset*/ ctx[2].apply(this, arguments);
					}))
				];

				mounted = true;
			}
		},
		p(new_ctx, [dirty]) {
			ctx = new_ctx;

			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 8) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[3], dirty, null, null);
				}
			}

			const formbuttons_changes = {};
			if (dirty & /*onSave*/ 2) formbuttons_changes.onSave = /*onSave*/ ctx[1];
			formbuttons.$set(formbuttons_changes);
		},
		i(local) {
			if (current) return;
			transition_in(default_slot, local);
			transition_in(formbuttons.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(default_slot, local);
			transition_out(formbuttons.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(form);
			if (default_slot) default_slot.d(detaching);
			destroy_component(formbuttons);
			mounted = false;
			run_all(dispose);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let { onSubmit } = $$props;
	let { onSave } = $$props;
	let { onReset } = $$props;

	$$self.$$set = $$props => {
		if ("onSubmit" in $$props) $$invalidate(0, onSubmit = $$props.onSubmit);
		if ("onSave" in $$props) $$invalidate(1, onSave = $$props.onSave);
		if ("onReset" in $$props) $$invalidate(2, onReset = $$props.onReset);
		if ("$$scope" in $$props) $$invalidate(3, $$scope = $$props.$$scope);
	};

	return [onSubmit, onSave, onReset, $$scope, slots];
}

class Form extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { onSubmit: 0, onSave: 1, onReset: 2 });
	}
}

export default Form;