import './FormButtons.css.proxy.js';
/* src/components/FormButtons.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	append,
	attr,
	detach,
	element,
	init,
	insert,
	is_function,
	listen,
	noop,
	safe_not_equal,
	space
} from "../../web_modules/svelte/internal.js";

function create_fragment(ctx) {
	let div;
	let button0;
	let t1;
	let button1;
	let t3;
	let button2;
	let mounted;
	let dispose;

	return {
		c() {
			div = element("div");
			button0 = element("button");
			button0.textContent = "Reset";
			t1 = space();
			button1 = element("button");
			button1.textContent = "Save";
			t3 = space();
			button2 = element("button");
			button2.textContent = "Submit";
			attr(button0, "type", "reset");
			attr(button0, "class", "svelte-1hc7q9y");
			attr(button1, "type", "button");
			attr(button1, "class", "svelte-1hc7q9y");
			attr(button2, "type", "submit");
			attr(button2, "class", "svelte-1hc7q9y");
			attr(div, "class", "buttonBar svelte-1hc7q9y");
		},
		m(target, anchor) {
			insert(target, div, anchor);
			append(div, button0);
			append(div, t1);
			append(div, button1);
			append(div, t3);
			append(div, button2);

			if (!mounted) {
				dispose = listen(button1, "click", function () {
					if (is_function(/*onSave*/ ctx[0])) /*onSave*/ ctx[0].apply(this, arguments);
				});

				mounted = true;
			}
		},
		p(new_ctx, [dirty]) {
			ctx = new_ctx;
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (detaching) detach(div);
			mounted = false;
			dispose();
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { onSave } = $$props;

	$$self.$$set = $$props => {
		if ("onSave" in $$props) $$invalidate(0, onSave = $$props.onSave);
	};

	return [onSave];
}

class FormButtons extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { onSave: 0 });
	}
}

export default FormButtons;