import './Question.css.proxy.js';
/* src/components/Question.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	add_render_callback,
	append,
	attr,
	bubble,
	destroy_each,
	detach,
	element,
	empty,
	init,
	insert,
	listen,
	noop,
	null_to_empty,
	run_all,
	safe_not_equal,
	select_multiple_value,
	select_option,
	select_options,
	select_value,
	set_data,
	set_input_value,
	space,
	text,
	to_number
} from "../../web_modules/svelte/internal.js";

function get_each_context_1(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[28] = list[i];
	return child_ctx;
}

function get_each_context(ctx, list, i) {
	const child_ctx = ctx.slice();
	child_ctx[28] = list[i];
	return child_ctx;
}

// (17:0) {#if show}
function create_if_block(ctx) {
	let if_block_anchor;

	function select_block_type(ctx, dirty) {
		if (/*type*/ ctx[11] === "checkbox") return create_if_block_1;
		return create_else_block;
	}

	let current_block_type = select_block_type(ctx, [-1]);
	let if_block = current_block_type(ctx);

	return {
		c() {
			if_block.c();
			if_block_anchor = empty();
		},
		m(target, anchor) {
			if_block.m(target, anchor);
			insert(target, if_block_anchor, anchor);
		},
		p(ctx, dirty) {
			if (current_block_type === (current_block_type = select_block_type(ctx, dirty)) && if_block) {
				if_block.p(ctx, dirty);
			} else {
				if_block.d(1);
				if_block = current_block_type(ctx);

				if (if_block) {
					if_block.c();
					if_block.m(if_block_anchor.parentNode, if_block_anchor);
				}
			}
		},
		d(detaching) {
			if_block.d(detaching);
			if (detaching) detach(if_block_anchor);
		}
	};
}

// (40:2) {:else}
function create_else_block(ctx) {
	let label_1;
	let span;
	let t0;
	let span_class_value;
	let t1;

	function select_block_type_1(ctx, dirty) {
		if (/*type*/ ctx[11] === "text") return create_if_block_2;
		if (/*type*/ ctx[11] === "textarea") return create_if_block_3;
		if (/*type*/ ctx[11] === "email") return create_if_block_4;
		if (/*type*/ ctx[11] === "select") return create_if_block_5;
		if (/*type*/ ctx[11] === "number") return create_if_block_8;
		if (/*type*/ ctx[11] === "date") return create_if_block_9;
	}

	let current_block_type = select_block_type_1(ctx, [-1]);
	let if_block = current_block_type && current_block_type(ctx);

	return {
		c() {
			label_1 = element("label");
			span = element("span");
			t0 = text(/*label*/ ctx[3]);
			t1 = space();
			if (if_block) if_block.c();
			attr(span, "class", span_class_value = "" + (null_to_empty(/*required*/ ctx[10] ? "required" : "") + " svelte-j7uns6"));
			attr(label_1, "class", "svelte-j7uns6");
		},
		m(target, anchor) {
			insert(target, label_1, anchor);
			append(label_1, span);
			append(span, t0);
			append(label_1, t1);
			if (if_block) if_block.m(label_1, null);
		},
		p(ctx, dirty) {
			if (dirty[0] & /*label*/ 8) set_data(t0, /*label*/ ctx[3]);

			if (dirty[0] & /*required*/ 1024 && span_class_value !== (span_class_value = "" + (null_to_empty(/*required*/ ctx[10] ? "required" : "") + " svelte-j7uns6"))) {
				attr(span, "class", span_class_value);
			}

			if (current_block_type === (current_block_type = select_block_type_1(ctx, dirty)) && if_block) {
				if_block.p(ctx, dirty);
			} else {
				if (if_block) if_block.d(1);
				if_block = current_block_type && current_block_type(ctx);

				if (if_block) {
					if_block.c();
					if_block.m(label_1, null);
				}
			}
		},
		d(detaching) {
			if (detaching) detach(label_1);

			if (if_block) {
				if_block.d();
			}
		}
	};
}

// (18:2) {#if type === 'checkbox'}
function create_if_block_1(ctx) {
	let label_1;
	let input;
	let t0;
	let span;
	let t1;
	let span_class_value;
	let mounted;
	let dispose;

	return {
		c() {
			label_1 = element("label");
			input = element("input");
			t0 = space();
			span = element("span");
			t1 = text(/*label*/ ctx[3]);
			attr(input, "type", "checkbox");
			input.required = /*required*/ ctx[10];
			attr(input, "class", "svelte-j7uns6");
			attr(span, "class", span_class_value = "" + (null_to_empty(/*required*/ ctx[10] ? "required" : "") + " svelte-j7uns6"));
			attr(label_1, "class", "svelte-j7uns6");
		},
		m(target, anchor) {
			insert(target, label_1, anchor);
			append(label_1, input);
			input.checked = /*checked*/ ctx[1];
			append(label_1, t0);
			append(label_1, span);
			append(span, t1);

			if (!mounted) {
				dispose = [
					listen(input, "change", /*input_change_handler*/ ctx[20]),
					listen(input, "change", /*change_handler*/ ctx[12])
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty[0] & /*required*/ 1024) {
				input.required = /*required*/ ctx[10];
			}

			if (dirty[0] & /*checked*/ 2) {
				input.checked = /*checked*/ ctx[1];
			}

			if (dirty[0] & /*label*/ 8) set_data(t1, /*label*/ ctx[3]);

			if (dirty[0] & /*required*/ 1024 && span_class_value !== (span_class_value = "" + (null_to_empty(/*required*/ ctx[10] ? "required" : "") + " svelte-j7uns6"))) {
				attr(span, "class", span_class_value);
			}
		},
		d(detaching) {
			if (detaching) detach(label_1);
			mounted = false;
			run_all(dispose);
		}
	};
}

// (97:32) 
function create_if_block_9(ctx) {
	let input;
	let mounted;
	let dispose;

	return {
		c() {
			input = element("input");
			attr(input, "type", "date");
			attr(input, "placeholder", /*placeholder*/ ctx[8]);
			attr(input, "min", /*min*/ ctx[6]);
			attr(input, "max", /*max*/ ctx[7]);
			input.required = /*required*/ ctx[10];
			attr(input, "class", "svelte-j7uns6");
		},
		m(target, anchor) {
			insert(target, input, anchor);
			set_input_value(input, /*value*/ ctx[0]);

			if (!mounted) {
				dispose = [
					listen(input, "input", /*input_input_handler_3*/ ctx[27]),
					listen(input, "change", /*change_handler_5*/ ctx[19])
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty[0] & /*placeholder*/ 256) {
				attr(input, "placeholder", /*placeholder*/ ctx[8]);
			}

			if (dirty[0] & /*min*/ 64) {
				attr(input, "min", /*min*/ ctx[6]);
			}

			if (dirty[0] & /*max*/ 128) {
				attr(input, "max", /*max*/ ctx[7]);
			}

			if (dirty[0] & /*required*/ 1024) {
				input.required = /*required*/ ctx[10];
			}

			if (dirty[0] & /*value, options*/ 33) {
				set_input_value(input, /*value*/ ctx[0]);
			}
		},
		d(detaching) {
			if (detaching) detach(input);
			mounted = false;
			run_all(dispose);
		}
	};
}

// (87:34) 
function create_if_block_8(ctx) {
	let input;
	let input_min_value;
	let input_max_value;
	let mounted;
	let dispose;

	return {
		c() {
			input = element("input");
			attr(input, "type", "number");
			attr(input, "placeholder", /*placeholder*/ ctx[8]);
			attr(input, "step", /*step*/ ctx[9]);
			attr(input, "min", input_min_value = Number(/*min*/ ctx[6] || 0) || undefined);
			attr(input, "max", input_max_value = Number(/*max*/ ctx[7] || 0) || undefined);
			input.required = /*required*/ ctx[10];
			attr(input, "class", "svelte-j7uns6");
		},
		m(target, anchor) {
			insert(target, input, anchor);
			set_input_value(input, /*value*/ ctx[0]);

			if (!mounted) {
				dispose = [
					listen(input, "input", /*input_input_handler_2*/ ctx[26]),
					listen(input, "change", /*change_handler_4*/ ctx[18])
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty[0] & /*placeholder*/ 256) {
				attr(input, "placeholder", /*placeholder*/ ctx[8]);
			}

			if (dirty[0] & /*step*/ 512) {
				attr(input, "step", /*step*/ ctx[9]);
			}

			if (dirty[0] & /*min*/ 64 && input_min_value !== (input_min_value = Number(/*min*/ ctx[6] || 0) || undefined)) {
				attr(input, "min", input_min_value);
			}

			if (dirty[0] & /*max*/ 128 && input_max_value !== (input_max_value = Number(/*max*/ ctx[7] || 0) || undefined)) {
				attr(input, "max", input_max_value);
			}

			if (dirty[0] & /*required*/ 1024) {
				input.required = /*required*/ ctx[10];
			}

			if (dirty[0] & /*value, options*/ 33 && to_number(input.value) !== /*value*/ ctx[0]) {
				set_input_value(input, /*value*/ ctx[0]);
			}
		},
		d(detaching) {
			if (detaching) detach(input);
			mounted = false;
			run_all(dispose);
		}
	};
}

// (69:34) 
function create_if_block_5(ctx) {
	let if_block_anchor;

	function select_block_type_2(ctx, dirty) {
		if (/*multi*/ ctx[4]) return create_if_block_6;
		return create_else_block_1;
	}

	let current_block_type = select_block_type_2(ctx, [-1]);
	let if_block = current_block_type(ctx);

	return {
		c() {
			if_block.c();
			if_block_anchor = empty();
		},
		m(target, anchor) {
			if_block.m(target, anchor);
			insert(target, if_block_anchor, anchor);
		},
		p(ctx, dirty) {
			if (current_block_type === (current_block_type = select_block_type_2(ctx, dirty)) && if_block) {
				if_block.p(ctx, dirty);
			} else {
				if_block.d(1);
				if_block = current_block_type(ctx);

				if (if_block) {
					if_block.c();
					if_block.m(if_block_anchor.parentNode, if_block_anchor);
				}
			}
		},
		d(detaching) {
			if_block.d(detaching);
			if (detaching) detach(if_block_anchor);
		}
	};
}

// (60:33) 
function create_if_block_4(ctx) {
	let input;
	let input_minlength_value;
	let input_maxlength_value;
	let mounted;
	let dispose;

	return {
		c() {
			input = element("input");
			attr(input, "type", "email");
			attr(input, "placeholder", /*placeholder*/ ctx[8]);
			attr(input, "minlength", input_minlength_value = Number(/*min*/ ctx[6] || 0) || undefined);
			attr(input, "maxlength", input_maxlength_value = Number(/*max*/ ctx[7] || 0) || undefined);
			input.required = /*required*/ ctx[10];
			attr(input, "class", "svelte-j7uns6");
		},
		m(target, anchor) {
			insert(target, input, anchor);
			set_input_value(input, /*value*/ ctx[0]);

			if (!mounted) {
				dispose = [
					listen(input, "input", /*input_input_handler_1*/ ctx[23]),
					listen(input, "change", /*change_handler_3*/ ctx[15])
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty[0] & /*placeholder*/ 256) {
				attr(input, "placeholder", /*placeholder*/ ctx[8]);
			}

			if (dirty[0] & /*min*/ 64 && input_minlength_value !== (input_minlength_value = Number(/*min*/ ctx[6] || 0) || undefined)) {
				attr(input, "minlength", input_minlength_value);
			}

			if (dirty[0] & /*max*/ 128 && input_maxlength_value !== (input_maxlength_value = Number(/*max*/ ctx[7] || 0) || undefined)) {
				attr(input, "maxlength", input_maxlength_value);
			}

			if (dirty[0] & /*required*/ 1024) {
				input.required = /*required*/ ctx[10];
			}

			if (dirty[0] & /*value, options*/ 33 && input.value !== /*value*/ ctx[0]) {
				set_input_value(input, /*value*/ ctx[0]);
			}
		},
		d(detaching) {
			if (detaching) detach(input);
			mounted = false;
			run_all(dispose);
		}
	};
}

// (52:36) 
function create_if_block_3(ctx) {
	let textarea;
	let textarea_minlength_value;
	let textarea_maxlength_value;
	let mounted;
	let dispose;

	return {
		c() {
			textarea = element("textarea");
			attr(textarea, "placeholder", /*placeholder*/ ctx[8]);
			attr(textarea, "minlength", textarea_minlength_value = Number(/*min*/ ctx[6] || 0) || undefined);
			attr(textarea, "maxlength", textarea_maxlength_value = Number(/*max*/ ctx[7] || 0) || undefined);
			textarea.required = /*required*/ ctx[10];
			attr(textarea, "class", "svelte-j7uns6");
		},
		m(target, anchor) {
			insert(target, textarea, anchor);
			set_input_value(textarea, /*value*/ ctx[0]);

			if (!mounted) {
				dispose = [
					listen(textarea, "input", /*textarea_input_handler*/ ctx[22]),
					listen(textarea, "change", /*change_handler_2*/ ctx[14])
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty[0] & /*placeholder*/ 256) {
				attr(textarea, "placeholder", /*placeholder*/ ctx[8]);
			}

			if (dirty[0] & /*min*/ 64 && textarea_minlength_value !== (textarea_minlength_value = Number(/*min*/ ctx[6] || 0) || undefined)) {
				attr(textarea, "minlength", textarea_minlength_value);
			}

			if (dirty[0] & /*max*/ 128 && textarea_maxlength_value !== (textarea_maxlength_value = Number(/*max*/ ctx[7] || 0) || undefined)) {
				attr(textarea, "maxlength", textarea_maxlength_value);
			}

			if (dirty[0] & /*required*/ 1024) {
				textarea.required = /*required*/ ctx[10];
			}

			if (dirty[0] & /*value, options*/ 33) {
				set_input_value(textarea, /*value*/ ctx[0]);
			}
		},
		d(detaching) {
			if (detaching) detach(textarea);
			mounted = false;
			run_all(dispose);
		}
	};
}

// (43:6) {#if type === 'text'}
function create_if_block_2(ctx) {
	let input;
	let input_minlength_value;
	let input_maxlength_value;
	let mounted;
	let dispose;

	return {
		c() {
			input = element("input");
			attr(input, "type", "text");
			attr(input, "placeholder", /*placeholder*/ ctx[8]);
			attr(input, "minlength", input_minlength_value = Number(/*min*/ ctx[6] || 0) || undefined);
			attr(input, "maxlength", input_maxlength_value = Number(/*max*/ ctx[7] || 0) || undefined);
			input.required = /*required*/ ctx[10];
			attr(input, "class", "svelte-j7uns6");
		},
		m(target, anchor) {
			insert(target, input, anchor);
			set_input_value(input, /*value*/ ctx[0]);

			if (!mounted) {
				dispose = [
					listen(input, "input", /*input_input_handler*/ ctx[21]),
					listen(input, "change", /*change_handler_1*/ ctx[13])
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty[0] & /*placeholder*/ 256) {
				attr(input, "placeholder", /*placeholder*/ ctx[8]);
			}

			if (dirty[0] & /*min*/ 64 && input_minlength_value !== (input_minlength_value = Number(/*min*/ ctx[6] || 0) || undefined)) {
				attr(input, "minlength", input_minlength_value);
			}

			if (dirty[0] & /*max*/ 128 && input_maxlength_value !== (input_maxlength_value = Number(/*max*/ ctx[7] || 0) || undefined)) {
				attr(input, "maxlength", input_maxlength_value);
			}

			if (dirty[0] & /*required*/ 1024) {
				input.required = /*required*/ ctx[10];
			}

			if (dirty[0] & /*value, options*/ 33 && input.value !== /*value*/ ctx[0]) {
				set_input_value(input, /*value*/ ctx[0]);
			}
		},
		d(detaching) {
			if (detaching) detach(input);
			mounted = false;
			run_all(dispose);
		}
	};
}

// (79:8) {:else}
function create_else_block_1(ctx) {
	let select;
	let option;
	let t_value = (/*placeholder*/ ctx[8] || "Select...") + "";
	let t;
	let mounted;
	let dispose;
	let each_value_1 = /*options*/ ctx[5];
	let each_blocks = [];

	for (let i = 0; i < each_value_1.length; i += 1) {
		each_blocks[i] = create_each_block_1(get_each_context_1(ctx, each_value_1, i));
	}

	return {
		c() {
			select = element("select");
			option = element("option");
			t = text(t_value);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			option.__value = "";
			option.value = option.__value;
			select.required = /*required*/ ctx[10];
			attr(select, "class", "svelte-j7uns6");
			if (/*value*/ ctx[0] === void 0) add_render_callback(() => /*select_change_handler_1*/ ctx[25].call(select));
		},
		m(target, anchor) {
			insert(target, select, anchor);
			append(select, option);
			append(option, t);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(select, null);
			}

			select_option(select, /*value*/ ctx[0]);

			if (!mounted) {
				dispose = [
					listen(select, "change", /*select_change_handler_1*/ ctx[25]),
					listen(select, "blur", /*blur_handler_1*/ ctx[17])
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (dirty[0] & /*placeholder*/ 256 && t_value !== (t_value = (/*placeholder*/ ctx[8] || "Select...") + "")) set_data(t, t_value);

			if (dirty[0] & /*options*/ 32) {
				each_value_1 = /*options*/ ctx[5];
				let i;

				for (i = 0; i < each_value_1.length; i += 1) {
					const child_ctx = get_each_context_1(ctx, each_value_1, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
					} else {
						each_blocks[i] = create_each_block_1(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(select, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}

				each_blocks.length = each_value_1.length;
			}

			if (dirty[0] & /*required*/ 1024) {
				select.required = /*required*/ ctx[10];
			}

			if (dirty[0] & /*value, options*/ 33) {
				select_option(select, /*value*/ ctx[0]);
			}
		},
		d(detaching) {
			if (detaching) detach(select);
			destroy_each(each_blocks, detaching);
			mounted = false;
			run_all(dispose);
		}
	};
}

// (70:8) {#if multi}
function create_if_block_6(ctx) {
	let select;
	let if_block_anchor;
	let mounted;
	let dispose;
	let if_block = !/*required*/ ctx[10] && create_if_block_7(ctx);
	let each_value = /*options*/ ctx[5];
	let each_blocks = [];

	for (let i = 0; i < each_value.length; i += 1) {
		each_blocks[i] = create_each_block(get_each_context(ctx, each_value, i));
	}

	return {
		c() {
			select = element("select");
			if (if_block) if_block.c();
			if_block_anchor = empty();

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].c();
			}

			select.multiple = true;
			select.required = /*required*/ ctx[10];
			attr(select, "class", "svelte-j7uns6");
			if (/*value*/ ctx[0] === void 0) add_render_callback(() => /*select_change_handler*/ ctx[24].call(select));
		},
		m(target, anchor) {
			insert(target, select, anchor);
			if (if_block) if_block.m(select, null);
			append(select, if_block_anchor);

			for (let i = 0; i < each_blocks.length; i += 1) {
				each_blocks[i].m(select, null);
			}

			select_options(select, /*value*/ ctx[0]);

			if (!mounted) {
				dispose = [
					listen(select, "change", /*select_change_handler*/ ctx[24]),
					listen(select, "blur", /*blur_handler*/ ctx[16])
				];

				mounted = true;
			}
		},
		p(ctx, dirty) {
			if (!/*required*/ ctx[10]) {
				if (if_block) {
					
				} else {
					if_block = create_if_block_7(ctx);
					if_block.c();
					if_block.m(select, if_block_anchor);
				}
			} else if (if_block) {
				if_block.d(1);
				if_block = null;
			}

			if (dirty[0] & /*options*/ 32) {
				each_value = /*options*/ ctx[5];
				let i;

				for (i = 0; i < each_value.length; i += 1) {
					const child_ctx = get_each_context(ctx, each_value, i);

					if (each_blocks[i]) {
						each_blocks[i].p(child_ctx, dirty);
					} else {
						each_blocks[i] = create_each_block(child_ctx);
						each_blocks[i].c();
						each_blocks[i].m(select, null);
					}
				}

				for (; i < each_blocks.length; i += 1) {
					each_blocks[i].d(1);
				}

				each_blocks.length = each_value.length;
			}

			if (dirty[0] & /*required*/ 1024) {
				select.required = /*required*/ ctx[10];
			}

			if (dirty[0] & /*value, options*/ 33) {
				select_options(select, /*value*/ ctx[0]);
			}
		},
		d(detaching) {
			if (detaching) detach(select);
			if (if_block) if_block.d();
			destroy_each(each_blocks, detaching);
			mounted = false;
			run_all(dispose);
		}
	};
}

// (82:12) {#each options as option}
function create_each_block_1(ctx) {
	let option;
	let t_value = /*option*/ ctx[28] + "";
	let t;
	let option_value_value;

	return {
		c() {
			option = element("option");
			t = text(t_value);
			option.__value = option_value_value = /*option*/ ctx[28];
			option.value = option.__value;
		},
		m(target, anchor) {
			insert(target, option, anchor);
			append(option, t);
		},
		p(ctx, dirty) {
			if (dirty[0] & /*options*/ 32 && t_value !== (t_value = /*option*/ ctx[28] + "")) set_data(t, t_value);

			if (dirty[0] & /*options*/ 32 && option_value_value !== (option_value_value = /*option*/ ctx[28])) {
				option.__value = option_value_value;
				option.value = option.__value;
			}
		},
		d(detaching) {
			if (detaching) detach(option);
		}
	};
}

// (72:12) {#if !required}
function create_if_block_7(ctx) {
	let option;

	return {
		c() {
			option = element("option");
			option.textContent = "(none)";
			option.__value = "";
			option.value = option.__value;
		},
		m(target, anchor) {
			insert(target, option, anchor);
		},
		d(detaching) {
			if (detaching) detach(option);
		}
	};
}

// (75:12) {#each options as option}
function create_each_block(ctx) {
	let option;
	let t_value = /*option*/ ctx[28] + "";
	let t;
	let option_value_value;

	return {
		c() {
			option = element("option");
			t = text(t_value);
			option.__value = option_value_value = /*option*/ ctx[28];
			option.value = option.__value;
		},
		m(target, anchor) {
			insert(target, option, anchor);
			append(option, t);
		},
		p(ctx, dirty) {
			if (dirty[0] & /*options*/ 32 && t_value !== (t_value = /*option*/ ctx[28] + "")) set_data(t, t_value);

			if (dirty[0] & /*options*/ 32 && option_value_value !== (option_value_value = /*option*/ ctx[28])) {
				option.__value = option_value_value;
				option.value = option.__value;
			}
		},
		d(detaching) {
			if (detaching) detach(option);
		}
	};
}

function create_fragment(ctx) {
	let if_block_anchor;
	let if_block = /*show*/ ctx[2] && create_if_block(ctx);

	return {
		c() {
			if (if_block) if_block.c();
			if_block_anchor = empty();
		},
		m(target, anchor) {
			if (if_block) if_block.m(target, anchor);
			insert(target, if_block_anchor, anchor);
		},
		p(ctx, dirty) {
			if (/*show*/ ctx[2]) {
				if (if_block) {
					if_block.p(ctx, dirty);
				} else {
					if_block = create_if_block(ctx);
					if_block.c();
					if_block.m(if_block_anchor.parentNode, if_block_anchor);
				}
			} else if (if_block) {
				if_block.d(1);
				if_block = null;
			}
		},
		i: noop,
		o: noop,
		d(detaching) {
			if (if_block) if_block.d(detaching);
			if (detaching) detach(if_block_anchor);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { show = true } = $$props;
	let { label } = $$props;
	let { value = undefined } = $$props;
	let { checked = false } = $$props;
	let { multi = false } = $$props;
	let { options = [] } = $$props;
	let { min = undefined } = $$props;
	let { max = undefined } = $$props;
	let { placeholder = undefined } = $$props;
	let { step = undefined } = $$props;
	let { required = true } = $$props;
	let { type = "text" } = $$props;

	function change_handler(event) {
		bubble($$self, event);
	}

	function change_handler_1(event) {
		bubble($$self, event);
	}

	function change_handler_2(event) {
		bubble($$self, event);
	}

	function change_handler_3(event) {
		bubble($$self, event);
	}

	function blur_handler(event) {
		bubble($$self, event);
	}

	function blur_handler_1(event) {
		bubble($$self, event);
	}

	function change_handler_4(event) {
		bubble($$self, event);
	}

	function change_handler_5(event) {
		bubble($$self, event);
	}

	function input_change_handler() {
		checked = this.checked;
		$$invalidate(1, checked);
	}

	function input_input_handler() {
		value = this.value;
		$$invalidate(0, value);
		$$invalidate(5, options);
	}

	function textarea_input_handler() {
		value = this.value;
		$$invalidate(0, value);
		$$invalidate(5, options);
	}

	function input_input_handler_1() {
		value = this.value;
		$$invalidate(0, value);
		$$invalidate(5, options);
	}

	function select_change_handler() {
		value = select_multiple_value(this);
		$$invalidate(0, value);
		$$invalidate(5, options);
	}

	function select_change_handler_1() {
		value = select_value(this);
		$$invalidate(0, value);
		$$invalidate(5, options);
	}

	function input_input_handler_2() {
		value = to_number(this.value);
		$$invalidate(0, value);
		$$invalidate(5, options);
	}

	function input_input_handler_3() {
		value = this.value;
		$$invalidate(0, value);
		$$invalidate(5, options);
	}

	$$self.$$set = $$props => {
		if ("show" in $$props) $$invalidate(2, show = $$props.show);
		if ("label" in $$props) $$invalidate(3, label = $$props.label);
		if ("value" in $$props) $$invalidate(0, value = $$props.value);
		if ("checked" in $$props) $$invalidate(1, checked = $$props.checked);
		if ("multi" in $$props) $$invalidate(4, multi = $$props.multi);
		if ("options" in $$props) $$invalidate(5, options = $$props.options);
		if ("min" in $$props) $$invalidate(6, min = $$props.min);
		if ("max" in $$props) $$invalidate(7, max = $$props.max);
		if ("placeholder" in $$props) $$invalidate(8, placeholder = $$props.placeholder);
		if ("step" in $$props) $$invalidate(9, step = $$props.step);
		if ("required" in $$props) $$invalidate(10, required = $$props.required);
		if ("type" in $$props) $$invalidate(11, type = $$props.type);
	};

	return [
		value,
		checked,
		show,
		label,
		multi,
		options,
		min,
		max,
		placeholder,
		step,
		required,
		type,
		change_handler,
		change_handler_1,
		change_handler_2,
		change_handler_3,
		blur_handler,
		blur_handler_1,
		change_handler_4,
		change_handler_5,
		input_change_handler,
		input_input_handler,
		textarea_input_handler,
		input_input_handler_1,
		select_change_handler,
		select_change_handler_1,
		input_input_handler_2,
		input_input_handler_3
	];
}

class Question extends SvelteComponent {
	constructor(options) {
		super();

		init(
			this,
			options,
			instance,
			create_fragment,
			safe_not_equal,
			{
				show: 2,
				label: 3,
				value: 0,
				checked: 1,
				multi: 4,
				options: 5,
				min: 6,
				max: 7,
				placeholder: 8,
				step: 9,
				required: 10,
				type: 11
			},
			[-1, -1]
		);
	}
}

export default Question;