import './Section.css.proxy.js';
/* src/components/Section.svelte generated by Svelte v3.29.0 */
import {
	SvelteComponent,
	append,
	attr,
	create_slot,
	detach,
	element,
	init,
	insert,
	safe_not_equal,
	set_data,
	space,
	text,
	transition_in,
	transition_out,
	update_slot
} from "../../web_modules/svelte/internal.js";

const get_footer_slot_changes_1 = dirty => ({});
const get_footer_slot_context_1 = ctx => ({});
const get_footer_slot_changes = dirty => ({});
const get_footer_slot_context = ctx => ({});
const get_headerXtra_slot_changes = dirty => ({});
const get_headerXtra_slot_context = ctx => ({});

// (10:10) Default slot content
function fallback_block_1(ctx) {
	let t;

	return {
		c() {
			t = text("Default slot content");
		},
		m(target, anchor) {
			insert(target, t, anchor);
		},
		d(detaching) {
			if (detaching) detach(t);
		}
	};
}

// (12:22)      
function fallback_block(ctx) {
	let div;
	let current;
	const footer_slot_template = /*#slots*/ ctx[2].footer;
	const footer_slot = create_slot(footer_slot_template, ctx, /*$$scope*/ ctx[1], get_footer_slot_context_1);

	return {
		c() {
			div = element("div");
			if (footer_slot) footer_slot.c();
			attr(div, "class", "footer");
		},
		m(target, anchor) {
			insert(target, div, anchor);

			if (footer_slot) {
				footer_slot.m(div, null);
			}

			current = true;
		},
		p(ctx, dirty) {
			if (footer_slot) {
				if (footer_slot.p && dirty & /*$$scope*/ 2) {
					update_slot(footer_slot, footer_slot_template, ctx, /*$$scope*/ ctx[1], dirty, get_footer_slot_changes_1, get_footer_slot_context_1);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(footer_slot, local);
			current = true;
		},
		o(local) {
			transition_out(footer_slot, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(div);
			if (footer_slot) footer_slot.d(detaching);
		}
	};
}

function create_fragment(ctx) {
	let section;
	let header;
	let h2;
	let t0;
	let t1;
	let t2;
	let div;
	let t3;
	let current;
	const headerXtra_slot_template = /*#slots*/ ctx[2].headerXtra;
	const headerXtra_slot = create_slot(headerXtra_slot_template, ctx, /*$$scope*/ ctx[1], get_headerXtra_slot_context);
	const default_slot_template = /*#slots*/ ctx[2].default;
	const default_slot = create_slot(default_slot_template, ctx, /*$$scope*/ ctx[1], null);
	const default_slot_or_fallback = default_slot || fallback_block_1(ctx);
	const footer_slot_template = /*#slots*/ ctx[2].footer;
	const footer_slot = create_slot(footer_slot_template, ctx, /*$$scope*/ ctx[1], get_footer_slot_context);
	const footer_slot_or_fallback = footer_slot || fallback_block(ctx);

	return {
		c() {
			section = element("section");
			header = element("header");
			h2 = element("h2");
			t0 = text(/*title*/ ctx[0]);
			t1 = space();
			if (headerXtra_slot) headerXtra_slot.c();
			t2 = space();
			div = element("div");
			if (default_slot_or_fallback) default_slot_or_fallback.c();
			t3 = space();
			if (footer_slot_or_fallback) footer_slot_or_fallback.c();
			attr(h2, "class", "svelte-r5qy1h");
			attr(header, "class", "svelte-r5qy1h");
			attr(div, "class", "content svelte-r5qy1h");
			attr(section, "class", "svelte-r5qy1h");
		},
		m(target, anchor) {
			insert(target, section, anchor);
			append(section, header);
			append(header, h2);
			append(h2, t0);
			append(header, t1);

			if (headerXtra_slot) {
				headerXtra_slot.m(header, null);
			}

			append(section, t2);
			append(section, div);

			if (default_slot_or_fallback) {
				default_slot_or_fallback.m(div, null);
			}

			append(section, t3);

			if (footer_slot_or_fallback) {
				footer_slot_or_fallback.m(section, null);
			}

			current = true;
		},
		p(ctx, [dirty]) {
			if (!current || dirty & /*title*/ 1) set_data(t0, /*title*/ ctx[0]);

			if (headerXtra_slot) {
				if (headerXtra_slot.p && dirty & /*$$scope*/ 2) {
					update_slot(headerXtra_slot, headerXtra_slot_template, ctx, /*$$scope*/ ctx[1], dirty, get_headerXtra_slot_changes, get_headerXtra_slot_context);
				}
			}

			if (default_slot) {
				if (default_slot.p && dirty & /*$$scope*/ 2) {
					update_slot(default_slot, default_slot_template, ctx, /*$$scope*/ ctx[1], dirty, null, null);
				}
			}

			if (footer_slot) {
				if (footer_slot.p && dirty & /*$$scope*/ 2) {
					update_slot(footer_slot, footer_slot_template, ctx, /*$$scope*/ ctx[1], dirty, get_footer_slot_changes, get_footer_slot_context);
				}
			} else {
				if (footer_slot_or_fallback && footer_slot_or_fallback.p && dirty & /*$$scope*/ 2) {
					footer_slot_or_fallback.p(ctx, dirty);
				}
			}
		},
		i(local) {
			if (current) return;
			transition_in(headerXtra_slot, local);
			transition_in(default_slot_or_fallback, local);
			transition_in(footer_slot_or_fallback, local);
			current = true;
		},
		o(local) {
			transition_out(headerXtra_slot, local);
			transition_out(default_slot_or_fallback, local);
			transition_out(footer_slot_or_fallback, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(section);
			if (headerXtra_slot) headerXtra_slot.d(detaching);
			if (default_slot_or_fallback) default_slot_or_fallback.d(detaching);
			if (footer_slot_or_fallback) footer_slot_or_fallback.d(detaching);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	let { title = "Default Title" } = $$props;

	$$self.$$set = $$props => {
		if ("title" in $$props) $$invalidate(0, title = $$props.title);
		if ("$$scope" in $$props) $$invalidate(1, $$scope = $$props.$$scope);
	};

	return [title, $$scope, slots];
}

class Section extends SvelteComponent {
	constructor(options) {
		super();
		init(this, options, instance, create_fragment, safe_not_equal, { title: 0 });
	}
}

export default Section;